## Ordinal Encoder

In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

C:\Users\panka\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [14]:
df = pd.read_csv("ordinal.csv")

In [15]:
df.head()

   Id  Education Country
0   1        PhD     USA
1   2    Masters      UK
2   3  Bachelors  Canada
3   4        PhD     USA
4   5    Masters     USA

In [4]:
df['Education'].unique()

array(['PhD', 'Masters', 'Bachelors'], dtype=object)

In [5]:
enc = OrdinalEncoder()

In [6]:
print(enc)

OrdinalEncoder()

In [8]:
enc.fit_transform(df[['Education']])

array([[2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.]])

In [9]:
df[['Education']] = enc.fit_transform(df[['Education']])

In [10]:
df.head()

   Id  Education Country
0   1        2.0     USA
1   2        1.0      UK
2   3        0.0  Canada
3   4        2.0     USA
4   5        1.0     USA

In [11]:
education = ['PhD', 'Masters', 'Bachelors']

In [12]:
enc = OrdinalEncoder(categories=[education])

In [16]:
enc.fit_transform(df[['Education']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.]])

In [18]:
df[['Education']] = enc.fit_transform(df[['Education']])

In [19]:
df.head()

   Id  Education Country
0   1        0.0     USA
1   2        1.0      UK
2   3        2.0  Canada
3   4        0.0     USA
4   5        1.0     USA